export type LOAD_PRODUCT = typeof LOAD_PRODUCT;
export const LOAD_PRODUCT = "LOAD_PRODUCT";

export const LOAD_ABOUT_US = "LOAD_ABOUT_US";
export type LOAD_ABOUT_US = typeof LOAD_ABOUT_US;

export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
export type ADD_PRODUCT_TO_BASKET = typeof ADD_PRODUCT_TO_BASKET;

export const REMOVE_PRODUCTS_FROM_BASKET = "REMOVE_PRODUCTS_FROM_BASKET";
export type REMOVE_PRODUCTS_FROM_BASKET = typeof REMOVE_PRODUCTS_FROM_BASKET;
